apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.name }}
  name: {{ .Values.name }}
spec:
  ports:
  - name: steam
    port: {{ .Values.port }}
    protocol: UDP
    targetPort: 27015
  - name: rcon
    port: {{ .Values.port }}
    protocol: TCP
    targetPort: 27015    
  selector:
    app: {{ .Values.name }}
  type: LoadBalancer
  loadBalancerIP: {{ .Values.ipaddress }}
